packages:
  - docs
  - theme
  - cli
  - plugins/*
  - examples/*
overrides:
  '@bufbuild/protobuf': ^2.5.2
  '@typescript-eslint/utils': ^8.34.1
  esbuild: ^0.25.5
  sass-embedded: ^1.89.2

patchedDependencies:
  floating-vue: patches/floating-vue.patch

catalogs:
  dev:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@pengzhanbo/eslint-config-vue': ^1.33.0
    '@pengzhanbo/stylelint-config': ^1.33.0
    '@simonwep/pickr': ^1.9.1
    '@types/express': ^5.0.3
    '@types/js-yaml': ^4.0.9
    '@types/less': ^3.0.8
    '@types/lodash.merge': ^4.6.9
    '@types/markdown-it': ^14.1.2
    '@types/minimist': ^1.2.5
    '@types/node': ^24.0.3
    '@types/stylus': ^0.48.43
    '@types/webpack-env': ^1.18.8
    '@vitest/coverage-istanbul': ^3.2.4
    bumpp: ^10.2.0
    commitizen: ^4.3.1
    conventional-changelog-cli: ^5.0.0
    cpx2: ^8.0.0
    cross-env: 7.0.3
    cz-conventional-changelog: ^3.3.0
    eslint: ^9.29.0
    http-server: ^14.1.1
    husky: ^9.1.7
    less: ^4.3.0
    lint-staged: ^16.1.2
    markdown-it: ^14.1.0
    memfs: ^4.17.2
    mermaid: ^11.6.0
    minimist: ^1.2.8
    rimraf: ^6.0.1
    stylelint: ^16.20.0
    stylus: ^0.64.0
    tsconfig-vuepress: ^7.0.0
    tsdown: ^0.12.8
    typescript: ^5.8.3
    vitest: ^3.2.4
    vue-router: ^4.5.1
    wait-on: ^8.0.3
  peer:
    '@iconify/json': ^2.2.350
    artplayer: ^5.2.3
    dashjs: ^5.0.3
    hls.js: ^1.6.5
    mathjax-full: ^3.2.2
    mpegts.js: 1.7.3
    pyodide: ^0.27.7
    sass: ^1.89.2
    sass-embedded: ^1.89.2
    swiper: ^11.2.8
  prod:
    '@clack/prompts': ^0.11.0
    '@iconify/utils': ^2.3.0
    '@iconify/vue': ^5.0.0
    '@mdit/plugin-attrs': ^0.23.0
    '@mdit/plugin-footnote': ^0.22.1
    '@mdit/plugin-mark': ^0.22.1
    '@mdit/plugin-sub': ^0.22.1
    '@mdit/plugin-sup': ^0.22.1
    '@mdit/plugin-tab': ^0.22.1
    '@mdit/plugin-tasklist': ^0.22.1
    '@pengzhanbo/utils': ^2.1.0
    '@vueuse/core': ^13.3.0
    '@vueuse/integrations': ^13.3.0
    bcrypt-ts: ^7.1.0
    cac: ^6.7.14
    chart.js: ^4.5.0
    chokidar: 3.6.0
    create-filter: ^1.1.0
    dayjs: ^1.11.13
    echarts: ^5.6.0
    esbuild: ^0.25.5
    fast-glob: ^3.3.3
    flowchart.ts: ^3.0.1
    focus-trap: ^7.6.5
    gray-matter: ^4.0.3
    handlebars: ^4.7.8
    image-size: ^2.0.2
    js-yaml: ^4.1.0
    katex: ^0.16.22
    local-pkg: ^1.1.1
    lru-cache: ^11.1.0
    magic-string: ^0.30.17
    mark.js: ^8.11.1
    markdown-it-container: ^4.0.0
    markmap-lib: ^0.18.12
    markmap-toolbar: ^0.18.12
    markmap-view: ^0.18.12
    minisearch: ^7.1.2
    nano-spawn: ^1.0.2
    nanoid: ^5.1.5
    os-locale: ^6.0.2
    p-map: ^7.0.3
    package-manager-detector: ^1.3.0
    picocolors: ^1.1.1
    shiki: ^3.6.0
    tinyglobby: 0.2.13
    tm-grammars: ^1.23.26
    tm-themes: ^1.10.6
    unplugin: ^2.3.5
    vue: ^3.5.17
  vuepress:
    '@vuepress/bundler-vite': 2.0.0-rc.23
    '@vuepress/helper': 2.0.0-rc.110
    '@vuepress/plugin-cache': 2.0.0-rc.103
    '@vuepress/plugin-comment': 2.0.0-rc.110
    '@vuepress/plugin-copy-code': 2.0.0-rc.110
    '@vuepress/plugin-docsearch': 2.0.0-rc.110
    '@vuepress/plugin-git': 2.0.0-rc.110
    '@vuepress/plugin-llms': 2.0.0-rc.110
    '@vuepress/plugin-markdown-chart': 2.0.0-rc.110
    '@vuepress/plugin-markdown-hint': 2.0.0-rc.110
    '@vuepress/plugin-markdown-image': 2.0.0-rc.110
    '@vuepress/plugin-markdown-include': 2.0.0-rc.110
    '@vuepress/plugin-markdown-math': 2.0.0-rc.110
    '@vuepress/plugin-nprogress': 2.0.0-rc.110
    '@vuepress/plugin-photo-swipe': 2.0.0-rc.110
    '@vuepress/plugin-reading-time': 2.0.0-rc.110
    '@vuepress/plugin-seo': 2.0.0-rc.110
    '@vuepress/plugin-shiki': 2.0.0-rc.110
    '@vuepress/plugin-sitemap': 2.0.0-rc.110
    '@vuepress/plugin-watermark': 2.0.0-rc.110
    '@vuepress/shiki-twoslash': 2.0.0-rc.110
    vuepress: 2.0.0-rc.23
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver
