packages:
  - docs
  - theme
  - cli
  - plugins/*
  - examples/*

overrides:
  '@bufbuild/protobuf': ^2.9.0
  '@typescript-eslint/utils': ^8.46.0
  esbuild: ^0.25.10
  sass-embedded: ^1.93.2

patchedDependencies:
  floating-vue: patches/floating-vue.patch

catalogs:
  dev:
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@lunariajs/core': ^0.1.1
    '@pengzhanbo/eslint-config-vue': ^1.38.0
    '@pengzhanbo/stylelint-config': ^1.38.0
    '@simonwep/pickr': ^1.9.1
    '@types/express': ^5.0.3
    '@types/js-yaml': ^4.0.9
    '@types/less': ^3.0.8
    '@types/lodash.merge': ^4.6.9
    '@types/markdown-it': ^14.1.2
    '@types/minimist': ^1.2.5
    '@types/node': ^24.7.0
    '@types/picomatch': ^4.0.2
    '@types/stylus': ^0.48.43
    '@types/webpack-env': ^1.18.8
    '@vitest/coverage-istanbul': ^3.2.4
    bumpp: ^10.3.1
    commitizen: ^4.3.1
    conventional-changelog-cli: ^5.0.0
    cpx2: ^8.0.0
    cross-env: 7.0.3
    cz-conventional-changelog: ^3.3.0
    eslint: ^9.37.0
    http-server: ^14.1.1
    husky: ^9.1.7
    less: ^4.4.2
    lint-staged: ^16.2.3
    markdown-it: ^14.1.0
    memfs: ^4.49.0
    mermaid: ^11.12.0
    minimist: ^1.2.8
    postcss: ^8.5.6
    rimraf: ^6.0.1
    stylelint: ^16.25.0
    stylus: ^0.64.0
    tsconfig-vuepress: ^7.0.0
    tsdown: ^0.15.6
    typescript: ^5.9.3
    vitest: ^3.2.4
    vue-router: ^4.5.1
    wait-on: ^9.0.1
  peer:
    '@iconify/json': ^2.2.393
    artplayer: ^5.3.0
    dashjs: ^5.0.3
    hls.js: ^1.6.13
    mathjax-full: ^3.2.2
    mpegts.js: 1.7.3
    pyodide: ^0.28.3
    sass: ^1.93.2
    sass-embedded: ^1.93.2
    swiper: ^12.0.2
  prod:
    '@clack/prompts': ^0.11.0
    '@iconify/utils': ^3.0.2
    '@iconify/vue': ^5.0.0
    '@mdit/plugin-attrs': ^0.23.1
    '@mdit/plugin-footnote': ^0.22.2
    '@mdit/plugin-mark': ^0.22.1
    '@mdit/plugin-sub': ^0.22.1
    '@mdit/plugin-sup': ^0.22.1
    '@mdit/plugin-tab': ^0.22.2
    '@mdit/plugin-tasklist': ^0.22.1
    '@pengzhanbo/utils': ^2.1.0
    '@vueuse/core': ^13.9.0
    '@vueuse/integrations': ^13.9.0
    bcrypt-ts: ^7.1.0
    cac: ^6.7.14
    chart.js: ^4.5.0
    chokidar: 4.0.3
    dayjs: ^1.11.18
    echarts: ^6.0.0
    esbuild: ^0.25.10
    flowchart.ts: ^3.0.1
    focus-trap: ^7.6.5
    gray-matter: ^4.0.3
    handlebars: ^4.7.8
    image-size: ^2.0.2
    js-yaml: ^4.1.0
    katex: ^0.16.23
    local-pkg: ^1.1.2
    lru-cache: ^11.2.2
    mark.js: ^8.11.1
    markdown-it-container: ^4.0.0
    markmap-lib: ^0.18.12
    markmap-toolbar: ^0.18.12
    markmap-view: ^0.18.12
    minisearch: ^7.2.0
    nano-spawn: ^1.0.3
    nanoid: ^5.1.6
    os-locale: ^6.0.2
    p-map: ^7.0.3
    package-manager-detector: ^1.4.0
    picocolors: ^1.1.1
    picomatch: ^4.0.3
    shiki: ^3.13.0
    tinyglobby: ^0.2.15
    tm-grammars: ^1.24.17
    tm-themes: ^1.10.9
    vue: ^3.5.22
  vuepress:
    '@vuepress/bundler-vite': 2.0.0-rc.24
    '@vuepress/helper': 2.0.0-rc.112
    '@vuepress/plugin-cache': 2.0.0-rc.112
    '@vuepress/plugin-comment': 2.0.0-rc.112
    '@vuepress/plugin-copy-code': 2.0.0-rc.112
    '@vuepress/plugin-docsearch': 2.0.0-rc.112
    '@vuepress/plugin-git': 2.0.0-rc.112
    '@vuepress/plugin-llms': 2.0.0-rc.112
    '@vuepress/plugin-markdown-chart': 2.0.0-rc.112
    '@vuepress/plugin-markdown-hint': 2.0.0-rc.112
    '@vuepress/plugin-markdown-image': 2.0.0-rc.112
    '@vuepress/plugin-markdown-include': 2.0.0-rc.112
    '@vuepress/plugin-markdown-math': 2.0.0-rc.112
    '@vuepress/plugin-nprogress': 2.0.0-rc.112
    '@vuepress/plugin-photo-swipe': 2.0.0-rc.112
    '@vuepress/plugin-reading-time': 2.0.0-rc.112
    '@vuepress/plugin-replace-assets': 2.0.0-rc.112
    '@vuepress/plugin-seo': 2.0.0-rc.112
    '@vuepress/plugin-shiki': 2.0.0-rc.112
    '@vuepress/plugin-sitemap': 2.0.0-rc.112
    '@vuepress/plugin-watermark': 2.0.0-rc.112
    '@vuepress/shiki-twoslash': 2.0.0-rc.112
    vuepress: 2.0.0-rc.24
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver
