packages:
  - docs
  - theme
  - cli
  - plugins/*
catalog:
  '@iconify/json': ^2.2.311
  '@vuepress/bundler-vite': 2.0.0-rc.20
  '@vuepress/helper': 2.0.0-rc.79
  '@vuepress/plugin-cache': 2.0.0-rc.79
  '@vuepress/plugin-comment': 2.0.0-rc.79
  '@vuepress/plugin-docsearch': 2.0.0-rc.79
  '@vuepress/plugin-git': 2.0.0-rc.79
  '@vuepress/plugin-markdown-hint': 2.0.0-rc.79
  '@vuepress/plugin-markdown-image': 2.0.0-rc.79
  '@vuepress/plugin-markdown-include': 2.0.0-rc.79
  '@vuepress/plugin-markdown-math': 2.0.0-rc.79
  '@vuepress/plugin-nprogress': 2.0.0-rc.79
  '@vuepress/plugin-photo-swipe': 2.0.0-rc.79
  '@vuepress/plugin-reading-time': 2.0.0-rc.79
  '@vuepress/plugin-seo': 2.0.0-rc.79
  '@vuepress/plugin-sitemap': 2.0.0-rc.79
  '@vuepress/plugin-watermark': 2.0.0-rc.79
  '@vueuse/core': ^12.7.0
  '@vueuse/integrations': ^12.7.0
  chokidar: 3.6.0
  fast-glob: ^3.3.3
  gray-matter: ^4.0.3
  json2yaml: ^1.1.0
  local-pkg: ^1.1.0
  nanoid: ^5.1.2
  vue: ^3.5.13
  vuepress: 2.0.0-rc.20
  vuepress-plugin-md-enhance: 2.0.0-rc.72
