catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - ua-parser-js
  - cached-factory
  - memfs
  - semver

packages:
  - docs
  - theme
  - cli
  - plugins/*
  - examples/*

patchedDependencies:
  floating-vue: patches/floating-vue.patch

catalogs:
  dev:
    '@commitlint/cli': ^20.4.1
    '@commitlint/config-conventional': ^20.4.1
    '@lunariajs/core': ^0.1.1
    '@pengzhanbo/eslint-config-vue': ^2.0.0
    '@pengzhanbo/stylelint-config': ^2.0.0
    '@simonwep/pickr': ^1.9.1
    '@types/express': ^5.0.6
    '@types/js-yaml': ^4.0.9
    '@types/less': ^3.0.8
    '@types/markdown-it': ^14.1.2
    '@types/minimist': ^1.2.5
    '@types/node': ^25.2.3
    '@types/picomatch': ^4.0.2
    '@types/qrcode': ^1.5.6
    '@types/stylus': ^0.48.43
    '@types/three': ^0.182.0
    '@types/webpack-env': ^1.18.8
    '@vitest/coverage-v8': ^4.0.18
    bumpp: ^10.4.1
    commitizen: ^4.3.1
    conventional-changelog-cli: ^5.0.0
    cpx2: ^8.0.0
    cross-env: 7.0.3
    cz-conventional-changelog: ^3.3.0
    eslint: ^10.0.0
    http-server: ^14.1.1
    husky: ^9.1.7
    less: ^4.5.1
    lint-staged: ^16.2.7
    markdown-it: ^14.1.1
    memfs: ^4.56.10
    mermaid: ^11.12.2
    minimist: ^1.2.8
    postcss: ^8.5.6
    rimraf: ^6.1.2
    stylelint: ^17.2.0
    stylus: ^0.64.0
    tsconfig-vuepress: ^7.0.0
    tsdown: ^0.20.3
    typescript: ^5.9.3
    vite: ^8.0.0-beta.14
    vitest: ^4.0.18
    wait-on: ^9.0.4
  peer:
    '@eslint-community/eslint-utils': ^4.9.1
    '@iconify/json': ^2.2.439
    '@mathjax/src': ^4.1.0
    '@pinyin-pro/data': ^1.3.0
    '@typescript-eslint/types': ^8.55.0
    '@typescript-eslint/utils': ^8.55.0
    artplayer: ^5.3.0
    dashjs: ^5.1.1
    gsap: ^3.14.2
    hls.js: ^1.6.15
    mpegts.js: 1.7.3
    ogl: ^1.0.11
    pinyin-pro: ^3.28.0
    postprocessing: ^6.38.2
    pyodide: ^0.29.3
    sass: ^1.97.3
    sass-embedded: ^1.97.3
    swiper: ^12.1.0
    three: ^0.182.0
  prod:
    '@clack/prompts': ^1.0.1
    '@iconify/utils': ^3.1.0
    '@iconify/vue': ^5.0.0
    '@mdit/plugin-attrs': ^0.24.2
    '@mdit/plugin-footnote': ^0.22.4
    '@mdit/plugin-mark': ^0.22.2
    '@mdit/plugin-sub': ^0.23.1
    '@mdit/plugin-sup': ^0.23.1
    '@mdit/plugin-tab': ^0.23.1
    '@mdit/plugin-tasklist': ^0.22.3
    '@pengzhanbo/utils': ^3.2.0
    '@vueuse/core': ^14.2.1
    '@vueuse/integrations': ^14.2.1
    cac: ^6.7.14
    chart.js: ^4.5.1
    chokidar: 5.0.0
    dayjs: ^1.11.19
    echarts: ^6.0.0
    esbuild: ^0.27.3
    flowchart.ts: ^3.0.1
    focus-trap: ^8.0.0
    gray-matter: ^4.0.3
    handlebars: ^4.7.8
    hash-wasm: ^4.12.0
    image-size: ^2.0.2
    js-yaml: ^4.1.1
    katex: ^0.16.28
    local-pkg: ^1.1.2
    lru-cache: ^11.2.6
    mark.js: ^8.11.1
    markdown-it-cjk-friendly: ^2.0.2
    markdown-it-container: ^4.0.0
    markmap-lib: ^0.18.12
    markmap-toolbar: ^0.18.12
    markmap-view: ^0.18.12
    minisearch: ^7.2.0
    nano-spawn: ^2.0.0
    nanoid: ^5.1.6
    os-locale: ^8.0.0
    p-map: ^7.0.4
    package-manager-detector: ^1.6.0
    picocolors: ^1.1.1
    picomatch: ^4.0.3
    qrcode: ^1.5.4
    shiki: ^3.22.0
    sort-package-json: ^3.6.1
    tm-grammars: ^1.30.8
    tm-themes: ^1.11.1
    vue: ^3.5.28
    vue-router: ^5.0.2
  vuepress:
    '@vuepress/bundler-vite': 2.0.0-rc.26
    '@vuepress/helper': 2.0.0-rc.123
    '@vuepress/plugin-cache': 2.0.0-rc.123
    '@vuepress/plugin-comment': 2.0.0-rc.123
    '@vuepress/plugin-copy-code': 2.0.0-rc.123
    '@vuepress/plugin-docsearch': 2.0.0-rc.123
    '@vuepress/plugin-git': 2.0.0-rc.123
    '@vuepress/plugin-llms': 2.0.0-rc.123
    '@vuepress/plugin-markdown-chart': 2.0.0-rc.123
    '@vuepress/plugin-markdown-hint': 2.0.0-rc.123
    '@vuepress/plugin-markdown-image': 2.0.0-rc.123
    '@vuepress/plugin-markdown-include': 2.0.0-rc.123
    '@vuepress/plugin-markdown-math': 2.0.0-rc.123
    '@vuepress/plugin-nprogress': 2.0.0-rc.123
    '@vuepress/plugin-photo-swipe': 2.0.0-rc.123
    '@vuepress/plugin-reading-time': 2.0.0-rc.123
    '@vuepress/plugin-replace-assets': 2.0.0-rc.123
    '@vuepress/plugin-seo': 2.0.0-rc.123
    '@vuepress/plugin-shiki': 2.0.0-rc.123
    '@vuepress/plugin-sitemap': 2.0.0-rc.123
    '@vuepress/plugin-watermark': 2.0.0-rc.123
    '@vuepress/shiki-twoslash': 2.0.0-rc.123
    vuepress: 2.0.0-rc.26

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver
  - less
