packages:
  - docs
  - theme
  - cli
  - plugins/*
catalog:
  '@iconify/json': ^2.2.280
  '@vuepress/bundler-vite': 2.0.0-rc.18
  '@vuepress/helper': 2.0.0-rc.63
  '@vuepress/plugin-cache': 2.0.0-rc.61
  '@vuepress/plugin-comment': 2.0.0-rc.63
  '@vuepress/plugin-docsearch': 2.0.0-rc.63
  '@vuepress/plugin-git': 2.0.0-rc.62
  '@vuepress/plugin-markdown-hint': 2.0.0-rc.63
  '@vuepress/plugin-markdown-image': 2.0.0-rc.63
  '@vuepress/plugin-markdown-include': 2.0.0-rc.63
  '@vuepress/plugin-markdown-math': 2.0.0-rc.63
  '@vuepress/plugin-nprogress': 2.0.0-rc.63
  '@vuepress/plugin-photo-swipe': 2.0.0-rc.63
  '@vuepress/plugin-reading-time': 2.0.0-rc.63
  '@vuepress/plugin-seo': 2.0.0-rc.63
  '@vuepress/plugin-sitemap': 2.0.0-rc.63
  '@vuepress/plugin-watermark': 2.0.0-rc.63
  '@vueuse/core': ^12.0.0
  '@vueuse/integrations': ^12.0.0
  chokidar: 3.6.0
  fast-glob: ^3.3.2
  gray-matter: ^4.0.3
  json2yaml: ^1.1.0
  local-pkg: ^0.5.1
  nanoid: ^5.0.9
  vue: ^3.5.13
  vuepress: 2.0.0-rc.18
