packages:
  - docs
  - theme
  - cli
  - plugins/*
  - examples/*

overrides:
  '@typescript-eslint/utils': ^8.32.0
  esbuild: ^0.25.4
  sass: ^1.88.0
  sass-embedded: ^1.88.0

catalogs:
  dev:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@pengzhanbo/eslint-config-vue': ^1.31.0
    '@pengzhanbo/stylelint-config': ^1.31.0
    '@simonwep/pickr': ^1.9.1
    '@types/express': ^5.0.1
    '@types/js-yaml': ^4.0.9
    '@types/less': ^3.0.8
    '@types/lodash.merge': ^4.6.9
    '@types/markdown-it': ^14.1.2
    '@types/minimist': ^1.2.5
    '@types/node': ^22.15.17
    '@types/stylus': ^0.48.43
    '@types/webpack-env': ^1.18.8
    '@vitest/coverage-istanbul': ^3.1.3
    bumpp: ^10.1.0
    commitizen: ^4.3.1
    conventional-changelog-cli: ^5.0.0
    cpx2: ^8.0.0
    cross-env: 7.0.3
    cz-conventional-changelog: ^3.3.0
    eslint: ^9.26.0
    http-server: ^14.1.1
    husky: ^9.1.7
    less: ^4.3.0
    lint-staged: ^16.0.0
    markdown-it: ^14.1.0
    memfs: ^4.17.1
    mermaid: ^11.6.0
    minimist: ^1.2.8
    rimraf: ^6.0.1
    stylelint: ^16.19.1
    stylus: ^0.64.0
    tsconfig-vuepress: ^7.0.0
    tsdown: ^0.11.5
    typescript: ^5.8.3
    vitest: ^3.1.3
    vue-router: ^4.5.1
    wait-on: ^8.0.3

  peer:
    '@iconify/json': ^2.2.337
    artplayer: ^5.2.3
    dashjs: ^5.0.1
    hls.js: ^1.6.2
    mathjax-full: ^3.2.2
    mpegts.js: 1.7.3
    sass: ^1.88.0
    sass-embedded: ^1.88.0
    sass-loader: ^16.0.5
    swiper: ^11.2.6

  prod:
    '@clack/prompts': ^0.10.1
    '@iconify/utils': ^2.3.0
    '@iconify/vue': ^5.0.0
    '@mdit/plugin-attrs': ^0.18.0
    '@mdit/plugin-footnote': ^0.18.0
    '@mdit/plugin-mark': ^0.18.0
    '@mdit/plugin-sub': ^0.18.0
    '@mdit/plugin-sup': ^0.18.0
    '@mdit/plugin-tab': ^0.18.0
    '@mdit/plugin-tasklist': ^0.18.0
    '@pengzhanbo/utils': ^2.1.0
    '@vueuse/core': ^13.1.0
    '@vueuse/integrations': ^13.1.0
    bcrypt-ts: ^7.0.0
    cac: ^6.7.14
    chart.js: ^4.4.9
    chokidar: 3.6.0
    create-filter: ^1.1.0
    dayjs: ^1.11.13
    echarts: ^5.6.0
    esbuild: ^0.25.4
    fast-glob: ^3.3.3
    flowchart.ts: ^3.0.1
    focus-trap: ^7.6.4
    gray-matter: ^4.0.3
    handlebars: ^4.7.8
    image-size: ^2.0.2
    js-yaml: ^4.1.0
    katex: ^0.16.22
    local-pkg: ^1.1.1
    lru-cache: ^11.1.0
    magic-string: ^0.30.17
    mark.js: ^8.11.1
    markdown-it-container: ^4.0.0
    markmap-lib: ^0.18.11
    markmap-toolbar: ^0.18.10
    markmap-view: ^0.18.10
    minisearch: ^7.1.2
    nano-spawn: ^1.0.1
    nanoid: ^5.1.5
    os-locale: ^6.0.2
    p-map: ^7.0.3
    package-manager-detector: ^1.3.0
    picocolors: ^1.1.1
    shiki: ^3.4.0
    tinyglobby: 0.2.13
    tm-grammars: ^1.23.18
    tm-themes: ^1.10.6
    unplugin: ^2.3.2
    vue: ^3.5.13

  vuepress:
    '@vuepress/bundler-vite': 2.0.0-rc.22
    '@vuepress/helper': 2.0.0-rc.99
    '@vuepress/plugin-cache': 2.0.0-rc.99
    '@vuepress/plugin-comment': 2.0.0-rc.99
    '@vuepress/plugin-copy-code': 2.0.0-rc.99
    '@vuepress/plugin-docsearch': 2.0.0-rc.99
    '@vuepress/plugin-git': 2.0.0-rc.99
    '@vuepress/plugin-markdown-hint': 2.0.0-rc.101
    '@vuepress/plugin-markdown-image': 2.0.0-rc.101
    '@vuepress/plugin-markdown-include': 2.0.0-rc.101
    '@vuepress/plugin-markdown-math': 2.0.0-rc.101
    '@vuepress/plugin-nprogress': 2.0.0-rc.99
    '@vuepress/plugin-photo-swipe': 2.0.0-rc.99
    '@vuepress/plugin-reading-time': 2.0.0-rc.99
    '@vuepress/plugin-seo': 2.0.0-rc.99
    '@vuepress/plugin-shiki': 2.0.0-rc.99
    '@vuepress/plugin-sitemap': 2.0.0-rc.99
    '@vuepress/plugin-watermark': 2.0.0-rc.99
    '@vuepress/shiki-twoslash': 2.0.0-rc.99
    vuepress: 2.0.0-rc.22
    vuepress-plugin-md-enhance: 2.0.0-rc.83

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver
