name: 新功能建议
description: 为该项目提出一个想法
title: '[Feature Request]'
labels:
  - enhancement
assignees: pengzhanbo
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 确保遵循以下陈述。
      options:
        - label: 我搜索了现有问题，没有其他人请求类似功能。
          required: true

        - label: 我认为25%以上的用户对此功能持积极态度。
          required: true

  - type: textarea
    id: feature
    attributes:
      label: 描述该功能
      description: 它有什么用，你为什么想要
      placeholder: 功能清晰简洁的描述，以及它将增强或解决的问题。例如，我总是感到困难，当 [...]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 附加上下文
      placeholder: 在此添加有关功能请求的任何其他上下文或截图。
