/**
 * Escape HTML special characters in a string. (note: `'` is not escaped, since all
 * attributes generated by this plugin are wrapped in double quotes)
 *
 * 转义字符串中的 HTML 特殊字符。（注意：不转义 `'`，因为本插件生成的属性均使用双引号包裹）
 *
 * @param value - The value to escape / 需要转义的字符串
 * @returns The escaped string / 转义后的字符串
 */
export function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
}
