/**
 * Multi-language presets for search plugin.
 *
 * 搜索插件的多语言预设。
 *
 * Language presets other than /zh/ and /en/ are generated by AI and may not be accurate.
 * If you find any errors, please submit an issue.
 *
 * 除 /zh/ 和 /en/ 外，其他语言预设通过 AI 生成，不保证准确。如有错误，欢迎提 issue。
 *
 * @module plugin-search/node/locales
 */
import type { DefaultLocaleInfo } from '@vuepress/helper'
import type { SearchLocaleOptions } from '../../shared/index.js'
import { deSearchLocale } from './de.js'
import { enSearchLocale } from './en.js'
import { frSearchLocale } from './fr.js'
import { jaSearchLocale } from './ja.js'
import { ruSearchLocale } from './ru.js'
import { zhTwSearchLocale } from './zh-tw.js'
import { zhSearchLocale } from './zh.js'

/**
 * Default locale configurations for search plugin.
 *
 * 搜索插件的默认语言配置。
 *
 * Maps language codes to their respective locale strings.
 *
 * 将语言代码映射到相应的本地化字符串。
 */
export const SEARCH_LOCALES: DefaultLocaleInfo<Partial<SearchLocaleOptions>> = [
  [['en', 'en-US'], enSearchLocale],
  [['zh', 'zh-CN', 'zh-Hans', 'zh-Hant'], zhSearchLocale],
  [['zh-TW'], zhTwSearchLocale],
  [['de', 'de-DE'], deSearchLocale],
  [['fr', 'fr-FR'], frSearchLocale],
  [['ru', 'ru-RU'], ruSearchLocale],
  [['ja', 'ja-JP'], jaSearchLocale],
]
