name: Update star history

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: pengzhanbo/star-history-action@v1
        with:
          repo: ${{ github.repository }}
          token: ${{ github.token }}
          theme: light, dark
          radar: true
          output-format: svg,png,json
